version: '3.8'
services:
  app:
    container_name: app-container
    restart: always
    build: .
    ports:
      - "3004:3004"
    depends_on:
      - mongo
  mongo:
    container_name: mongo-backend
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - backendDB:/data/backendDB

volumes:
  backendDB: